server:
  port: 10000
  servlet:
    context-path: /app-one-api/
spring:
  application:
    name: app-one-services
  datasource:
    url: jdbc:h2:mem:hr;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:scripts/load.sql';
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-database
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    service-url:
      defaultZone: http://10.6.221.129:10003/eureka
      
app-two-services:
   ribbon:
    listOfServers: localhost:10001, localhost:10002